MainWidget:
	
<MainWidet>:
	orientation: "vertical"
	Label:
		text: root.label_text
		text_size: root.width/1.2, None
		font_size: "20dp"
		color: 1,0.5,1,1
		
	Button:
		text: "Update"
		on_release: root.get_image_url()
	
<MainWidget>:
	orientation: "vertical"
	#AsyncImage:
	#	source: root.img_src
	#	size: self.texture_size
	
	BoxLayout:
		orientation: "vertical"
		size_hint: 1, 0.3
		spacing: "10dp"
		Label:
			text: root.label_text
			font_size: "15dp"
			color: 0, 1, 1, 1
			text_size: self.size
			halign: "center"
			valign: "bottom"
			font_name: "comic.otf"
			
		Button:
			text: "get new image"
			on_release: root.get_image_url()
			size_hint: 1, 0.5
			background_normal: ''
			background_color: 0, 1, 0, 1
			color: 0, 0, 0, 1
			font_size: "18dp"
			font_name: "comic.otf"
		

<TopLogo>:
	text: "XKCD comics"
	font_size: "25dp"
	size_hint: 1, 0.1
	font_name: "risalah.otf"
